# cards.py
# all the cards in the game


unimplemented_cards = [
    # Elements
    "Rock", "Paper", "Scissors", "Fire", "Water", "Wind", "Earth", "Lightning",
    "Ice", "Shadow", "Light", "Void",
    # Units
    "Knight", "Archer", "Mage", "Dragon", "Goblin", "Shield",
    "Rogue", "Paladin", "Necromancer", "Berserker", "Ranger", "Druid",
    # Suited (standard)
    "Ace of Spades", "King of Hearts", "Queen of Diamonds", "Jack of Clubs",
    "Ten of Spades",  "Nine of Hearts", "Eight of Diamonds", "Seven of Clubs",
    # Spells
    "Fireball", "Blizzard", "Thunderstrike", "Heal", "Barrier", "Summon",
    "Curse", "Bless", "Teleport", "Drain",
]

CARD_DESCRIPTIONS = {
    # Elements
    "Rock":          "The classic. Solid and dependable. Crushes through with brute force.",
    "Paper":         "Covers Rock and disproves Spock. Deceptively powerful.",
    "Scissors":      "Sharp and precise. Cuts through Paper with ease.",
    "Fire":          "Primal flame that consumes all. Burns through defenses.",
    "Water":         "The great equalizer. Extinguishes fire and erodes stone.",
    "Wind":          "Invisible force of nature. Carries storms and fuels flames.",
    "Earth":         "Solid and unyielding. The foundation upon which all is built.",
    "Lightning":     "Raw electrical energy. Strikes fast and devastates.",
    "Ice":           "Frozen power that slows and shatters. Chilling precision.",
    "Shadow":        "Darkness incarnate. Strikes from where you least expect.",
    "Light":         "Radiant energy that pierces darkness. Purifies and reveals.",
    "Void":          "The absence of everything. Consumes matter and energy alike.",
    # Units
    "Knight":        "Mounted warrior with lance and honor. Charges through enemy lines.",
    "Archer":        "Ranged combatant with deadly aim. Picks off threats from afar.",
    "Mage":          "Channels arcane magic. Versatile and unpredictable in combat.",
    "Dragon":        "A mighty beast of fire and fury. Dominates the skies.",
    "Goblin":        "Small but cunning. Overwhelms foes with numbers and tricks.",
    "Shield":        "Pure defense. Absorbs damage and protects allies.",
    "Rogue":         "Strikes from the shadows. Quick, silent, and deadly.",
    "Paladin":       "Holy warrior combining faith and steel. Heals and fights.",
    "Necromancer":   "Raises the dead to fight. Dark magic at its finest.",
    "Berserker":     "Uncontrollable rage fuels devastating attacks. All offense.",
    "Ranger":        "Master of the wilderness. Tracks and ambushes with precision.",
    "Druid":         "Nature's champion. Shapeshifts and commands the wild.",
    # Suited
    "Ace of Spades":      "The highest card. A symbol of power and finality.",
    "King of Hearts":     "The benevolent ruler. Strong leadership on the field.",
    "Queen of Diamonds":  "Elegant and sharp. Wealth becomes a weapon.",
    "Jack of Clubs":      "The resourceful knave. Tricks and cunning in play.",
    "Ten of Spades":      "A solid foundation. Reliable and consistent.",
    "Nine of Hearts":     "The wish card. Brings hope and unexpected turns.",
    "Eight of Diamonds":  "Steady and balanced. A dependable mid-range card.",
    "Seven of Clubs":     "Lucky number seven. Fortune favors the bold.",
    # Spells
    "Fireball":      "A blazing sphere of destruction. Deals massive area damage.",
    "Blizzard":      "A freezing storm that slows and damages all enemies.",
    "Thunderstrike": "A bolt from above. Precise and devastating single-target.",
    "Heal":          "Restores health to an ally. Essential for survival.",
    "Barrier":       "Creates a protective shield. Blocks incoming damage.",
    "Summon":        "Calls forth a creature to aid in battle.",
    "Curse":         "Weakens an enemy with dark magic. Reduces their power.",
    "Bless":         "Empowers an ally with divine energy. Boosts their strength.",
    "Teleport":      "Instantly moves a unit to a new position. Tactical repositioning.",
    "Drain":         "Siphons life force from an enemy. Heals you as it hurts them.",
}


ALL_CARDS = [

    # -- card backs ---
    {"name": "Default Back",      "image": "assets/cards/back/card_back_default.png",      "category": "Card Backs", "desc": "The standard card back design. Classic and timeless."},
    {"name": "Red Back",      "image": "assets/cards/back/red_back.png",      "category": "Card Backs", "desc": "A vibrant red card back. Bold and energetic."},
    {"name": "Red Design Back",      "image": "assets/cards/back/red_design_back.png",      "category": "Card Backs", "desc": "A red card back with intricate patterns. Elegant and eye-catching."},
    {"name": "Bicycle Design Back",      "image": "assets/cards/back/card_bicycle_back.png",      "category": "Card Backs", "desc": "A card back inspired by classic Bicycle playing cards. Nostalgic and stylish."},



    # card rarities
    {"name": "Common",         "image": "assets/cards/rarity/card_common.png",         "category": "Rarity", "desc": "The most basic cards. Easy to find and collect."},
    {"name": "Uncommon",       "image": "assets/cards/rarity/card_uncommon.png",       "category": "Rarity", "desc": "Slightly rarer than common cards. A bit more powerful."},
    {"name": "Rare",           "image": "assets/cards/rarity/card_rare.png",           "category": "Rarity", "desc": "Harder to find. Contains stronger cards."},
    {"name": "Epic",           "image": "assets/cards/rarity/card_epic.png",           "category": "Rarity", "desc": "Very difficult to find. Contains the most powerful cards."},
    {"name": "Uncommon - Gold Trim",     "image": "assets/cards/rarity/card_uncommon_gold_trim.png",      "category": "Rarity", "desc": "Very difficult to obtain. Adds a luxurious gold border to your cards."},



    # --- Core Elements ---
    {"name": "Rock",            "image": "assets/card_rock.png",            "category": "Core", "desc": "The classic. Strong against Scissors and Lizard, weak to Paper and Spock."},
    {"name": "Paper",           "image": "assets/card_paper.png",           "category": "Core", "desc": "Covers Rock and disproves Spock. Weak to Scissors and Lizard."},
    {"name": "Scissors",        "image": "assets/card_scissors.png",        "category": "Core", "desc": "Cuts Paper and decapitates Lizard. Weak to Rock and Spock."},
    {"name": "Snake",           "image": "assets/card_snake.png",           "category": "Core", "desc": "A slithering predator. Strikes swiftly and poisons its foes."},
    {"name": "Human",           "image": "assets/card_human.png",           "category": "Core", "desc": "The adaptable species. Uses tools and cunning to overcome obstacles."},
    {"name": "Dragon",          "image": "assets/card_dragon.png",          "category": "Core", "desc": "A mighty beast of fire and fury. Dominates the skies with raw power."},
    {"name": "Wolf",            "image": "assets/card_wolf.png",            "category": "Core", "desc": "Pack hunter with sharp instincts. Overwhelms foes through teamwork."},
    {"name": "Devil",           "image": "assets/card_devil.png",           "category": "Core", "desc": "A dark entity of chaos. Corrupts and undermines all who oppose it."},
    {"name": "Lightning",       "image": "assets/card_lightning.png",       "category": "Core", "desc": "Pure electrical energy. Strikes fast and leaves devastation in its wake."},
    {"name": "Gun",             "image": "assets/card_gun.png",             "category": "Core", "desc": "Modern firepower. Delivers precise, ranged damage to any target."},
    {"name": "Fire",            "image": "assets/card_fire.png",            "category": "Core", "desc": "Primal element of destruction. Burns through organic matter with ease."},
    {"name": "Water",           "image": "assets/card_water.png",           "category": "Core", "desc": "The life-giving element. Extinguishes fire and erodes stone over time."},
    {"name": "Air",             "image": "assets/card_air.png",             "category": "Core", "desc": "Invisible but powerful. Fuels fire and carries storms across the land."},
    {"name": "Sponge",          "image": "assets/card_sponge.png",          "category": "Core", "desc": "Absorbent and resilient. Soaks up water and smothers fire."},
    {"name": "Tree",            "image": "assets/card_tree.png",            "category": "Core", "desc": "Rooted and enduring. Draws strength from earth and shelters life."},
    {"name": "Lizard",          "image": "assets/card_lizard.png",          "category": "Core", "desc": "Poisons Spock and eats Paper. A cunning reptilian survivor."},
    {"name": "Spock",           "image": "assets/card_spock.png",           "category": "Core", "desc": "Smashes Scissors and vaporizes Rock. Logic is his greatest weapon."},
    {"name": "Earth",           "image": "assets/card_earth.png",           "category": "Core", "desc": "The foundation of all. Immovable and enduring against most forces."},
    {"name": "Metal",           "image": "assets/card_metal.png",           "category": "Core", "desc": "Forged and unyielding. Resists blows and conducts lightning."},
    {"name": "Bear",            "image": "assets/card_bear.png",            "category": "Core", "desc": "Raw brute strength. Overpowers most creatures in close combat."},
    {"name": "Computer",        "image": "assets/card_computer.png",        "category": "Core", "desc": "Calculates optimal strategies. Outthinks opponents with pure logic."},
    {"name": "Balance",         "image": "assets/card_balance.png",         "category": "Core", "desc": "Restores equilibrium. Neutralizes extreme advantages on either side."},
    {"name": "Void",            "image": "assets/card_void.png",            "category": "Core", "desc": "The absence of everything. Consumes matter and energy alike."},
    {"name": "Super Paper",     "image": "assets/card_super_paper.png",     "category": "Core", "desc": "An enhanced version of Paper with amplified covering power."},
    {"name": "Skissors",        "image": "assets/card_skissors.png",        "category": "Core", "desc": "A twisted variant of Scissors. Unpredictable and dangerously sharp."},
    # --- Toon ---
    {"name": "Toon Spock",      "image": "assets/card_toon_spock.png",      "category": "Toon", "desc": "A cartoonish Spock. Same logic, but with a playful twist."},
    {"name": "Toon Snake",      "image": "assets/card_toon_snake.png",      "category": "Toon", "desc": "A goofy serpent from Toon World. Silly but still venomous."},
    {"name": "Toon Lizard",     "image": "assets/card_toon_lizard.png",     "category": "Toon", "desc": "A comical lizard with big eyes. Don't underestimate its bite."},
    {"name": "Toon Metal",      "image": "assets/card_toon_metal.png",      "category": "Toon", "desc": "Shiny cartoon metal. Bounces attacks back with a comedic clang."},
    {"name": "Toon Angel",      "image": "assets/card_toon_angel.png",      "category": "Toon", "desc": "A whimsical angel from Toon World. Heals allies with cartoon magic."},
    {"name": "Toon Fire",       "image": "assets/card_toon_fire.png",       "category": "Toon", "desc": "Animated flames that dance and giggle. Still burns, though!"},
    {"name": "Toon Water",      "image": "assets/card_toon_water.png",      "category": "Toon", "desc": "A bubbly splash of cartoon water. Playful but effective."},
    {"name": "Toon Earth",      "image": "assets/card_toon_earth.png",      "category": "Toon", "desc": "A bouncy cartoon planet. Surprisingly heavy when it lands on you."},
    {"name": "Toon Dragon",     "image": "assets/card_toon_dragon.png",     "category": "Toon", "desc": "A cute but fierce cartoon dragon. Breathes rainbow fire."},
    {"name": "Toon Gun",        "image": "assets/card_toon_gun.png",        "category": "Toon", "desc": "A toy-like gun that shoots cork bullets. Comedic but startling."},
    {"name": "Toon T.O.C.",     "image": "assets/card_toon_table_of_contents.png", "category": "Toon", "desc": "Table of Contents for Toon World. Organizes all toon cards."},
    {"name": "Toon Bookmark",   "image": "assets/card_toon_bookmark.png",   "category": "Toon", "desc": "Marks a page in Toon World. Lets you return to a saved state."},
    {"name": "Toon World",      "image": "assets/card_toon_world.png",      "category": "Toon", "desc": "The magical storybook realm. All Toon cards gain power here."},
    {"name": "Toon Kingdom",    "image": "assets/card_toon_kingdom.png",    "category": "Toon", "desc": "An upgraded Toon World. Protects Toon monsters from destruction."},
    # --- Special / Rule Cards ---
    {"name": "No Lose",         "image": "assets/card_no_lose.png",         "category": "Special", "desc": "Prevents you from losing this round. A powerful safety net."},
    {"name": "Stop Card",       "image": "assets/card_stop_card.png",       "category": "Special", "desc": "Halts the opponent's action for one turn. Buys precious time."},
    {"name": "Counter Stop",    "image": "assets/card_counter_stop.png",    "category": "Special", "desc": "Negates a Stop Card. Keeps your momentum going."},
    {"name": "Fundamentals",    "image": "assets/card_fundamentals_only.png","category": "Special", "desc": "Restricts play to core elements only. Strips away all extras."},
    {"name": "Non-Core",        "image": "assets/card_non_core.png",         "category": "Special", "desc": "Allows only non-core cards to be played this round."},
    {"name": "Reload",          "image": "assets/card_reload.png",           "category": "Special", "desc": "Refreshes your hand. Draw new cards to replace current ones."},
    {"name": "Magical Mallet",  "image": "assets/card_magical_mallet.png",   "category": "Special", "desc": "Shuffle chosen cards back into the deck and draw the same number."},
    {"name": "Jar of Greed",    "image": "assets/card_jar_of_greed.png",     "category": "Special", "desc": "Draw one extra card from your deck. Simple but effective."},
    
    

    # --- Exodia ---
    {"name": "Exodia",          "image": "assets/card_exodia_the_forbidden_one.png", "category": "Exodia", "desc": "The Forbidden One. Collect all pieces to achieve an instant victory."},
    {"name": "Full Exodia",     "image": "assets/card_full_exodia.png",      "category": "Exodia", "desc": "The complete Exodia assembled. Unleashes unstoppable obliteration."},
    {"name": "Left Arm",        "image": "assets/card_left_arm_of_exodia.png","category": "Exodia", "desc": "Left Arm of the Forbidden One. One of five pieces needed for Exodia."},
    {"name": "Right Arm",       "image": "assets/card_right_arm_of_exodia.png","category": "Exodia", "desc": "Right Arm of the Forbidden One. One of five pieces needed for Exodia."},
    {"name": "Left Leg",        "image": "assets/card_left_leg_of_exodia.png","category": "Exodia", "desc": "Left Leg of the Forbidden One. One of five pieces needed for Exodia."},
    {"name": "Right Leg",       "image": "assets/card_right_leg_of_exodia.png","category": "Exodia", "desc": "Right Leg of the Forbidden One. One of five pieces needed for Exodia."},
    {"name": "Tassets",         "image": "assets/card_tassets_of_exodia.png", "category": "Exodia", "desc": "Tassets of Exodia. Protective armor piece of the Forbidden One."},
    {"name": "Shadow Exodia",   "image": "assets/card_shadow_of_exodia.png",  "category": "Exodia", "desc": "A dark reflection of Exodia. Mimics the Forbidden One's power."},
    {"name": "Stop Exodia",     "image": "assets/card_stop_exodia.png",       "category": "Exodia", "desc": "Prevents Exodia from being summoned. The ultimate counter."},
    {"name": "Pot of Greed",    "image": "assets/card_pot_of_greed.png",      "category": "Exodia", "desc": "Draw two additional cards. A staple for any Exodia strategy."},


    # --- MOBA cards ---
    {"name": "Safelane",          "image": "assets/card_aaa_moba_safelane.png", "category": "MOBA", "desc": "The safe path in the game. Provides a secure route for your units."},
    {"name": "Midlane",          "image": "assets/card_aaa_moba_midlane.png", "category": "MOBA", "desc": "The midlane."},
    {"name": "Offlane",          "image": "assets/card_aaa_moba_offlane.png", "category": "MOBA", "desc": "The offlane."},
    {"name": "Soft Support",          "image": "assets/card_aaa_moba_soft_support.png", "category": "MOBA", "desc": "Provides support and utility to teammates."},
    {"name": "Hard Support",          "image": "assets/card_aaa_moba_hard_support.png", "category": "MOBA", "desc": "Provides heavy support and crowd control to teammates."},
    
    {"name": "Tri-lane Support",          "image": "assets/card_aaa_moba_tri_lane_support.png", "category": "MOBA", "desc": "The 3rd support."},
    {"name": "Sapport",          "image": "assets/card_aaa_moba_sapport.png", "category": "MOBA", "desc": "The sapport."},
    {"name": "Suicide Lane",          "image": "assets/card_aaa_moba_suicide_lane.png", "category": "MOBA", "desc": "The suicide lane."},
    {"name": "Death Lane",          "image": "assets/card_aaa_moba_death_lane.png", "category": "MOBA", "desc": "The death lane."},
    {"name": "Tri-laner",          "image": "assets/card_aaa_moba_tri_laner.png", "category": "MOBA", "desc": "The tri-laner."},
    
    {"name": "Jungle",          "image": "assets/card_aaa_moba_jungle.png", "category": "MOBA", "desc": "The role that jungles."},
    {"name": "Roaming",          "image": "assets/card_aaa_moba_roaming.png", "category": "MOBA", "desc": "The role that roams."},
    {"name": "Roaming Support",          "image": "assets/card_aaa_moba_roaming.png", "category": "MOBA", "desc": "The role that supports the roaming."},
    

    {"name": "Marksman",          "image": "assets/card_aaa_moba_marksman.png", "category": "MOBA", "desc": "The marksman."},
    {"name": "Mid laner",          "image": "assets/card_aaa_moba_mid_laner.png", "category": "MOBA", "desc": "The mid laner."},
    {"name": "Top laner",          "image": "assets/card_aaa_moba_top_laner.png", "category": "MOBA", "desc": "The top laner."},
    {"name": "Support",          "image": "assets/card_aaa_moba_support.png", "category": "MOBA", "desc": "The support."},
    {"name": "Jungler",          "image": "assets/card_aaa_moba_jungler.png", "category": "MOBA", "desc": "The jungler."},
    {"name": "River",          "image": "assets/card_aaa_moba_river.png", "category": "MOBA", "desc": "The riverer."},
    
    
    {"name": "Position 1",          "image": "assets/card_aaa_moba_position_1.png", "category": "MOBA", "desc": "The position 1."},
    {"name": "Position 2",          "image": "assets/card_aaa_moba_position_2.png", "category": "MOBA", "desc": "The position 2."},
    {"name": "Position 3",          "image": "assets/card_aaa_moba_position_3.png", "category": "MOBA", "desc": "The position 3."},
    {"name": "Position 4",          "image": "assets/card_aaa_moba_position_4.png", "category": "MOBA", "desc": "The position 4."},
    {"name": "Position 5",          "image": "assets/card_aaa_moba_position_5.png", "category": "MOBA", "desc": "The position 5."},
    {"name": "Position 6",          "image": "assets/card_aaa_moba_position_6.png", "category": "MOBA", "desc": "The position 6."},
    {"name": "Position 0",          "image": "assets/card_aaa_moba_position_0.png", "category": "MOBA", "desc": "The position 0."},

    # --- playing cards ---
    {"name": "♠ Ace of Spades",     "image": "assets/cards/Spade/A.png",      "category": "Playing Cards", "desc": "The Ace of Spades. The highest card in the deck, often associated with good luck and power."},
    {"name": "♠ King of Spades",    "image": "assets/cards/Spade/K.png",      "category": "Playing Cards", "desc": "The King of Spades. A symbol of authority and strength, wielding the sword with honor."},
    {"name": "♠ Queen of Spades",   "image": "assets/cards/Spade/Q.png",      "category": "Playing Cards", "desc": "The Queen of Spades. A symbol of wisdom and strategy, often associated with mystery."},
    {"name": "♠ Jack of Spades",    "image": "assets/cards/Spade/J.png",      "category": "Playing Cards", "desc": "The Jack of Spades. A symbol of cunning and wit, often depicted as a clever rogue."},
    {"name": "♠ Ten of Spades",     "image": "assets/cards/Spade/10.png",     "category": "Playing Cards", "desc": "The Ten of Spades. Represents completion and fulfillment, often associated with victory."},
    {"name": "♠ Nine of Spades",    "image": "assets/cards/Spade/9.png",      "category": "Playing Cards", "desc": "The Nine of Spades. A card of reflection and introspection, symbolizing inner strength."},
    {"name": "♠ Eight of Spades",   "image": "assets/cards/Spade/8.png",      "category": "Playing Cards", "desc": "The Eight of Spades. Represents balance and infinity, often associated with cycles."},
    {"name": "♠ Seven of Spades",   "image": "assets/cards/Spade/7.png",      "category": "Playing Cards", "desc": "The Seven of Spades. A magical number, often associated with luck and mystery."},
    {"name": "♠ Six of Spades",     "image": "assets/cards/Spade/6.png",      "category": "Playing Cards", "desc": "The Six of Spades. Represents harmony and balance, a card of negotiation."},
    {"name": "♠ Five of Spades",    "image": "assets/cards/Spade/5.png",      "category": "Playing Cards", "desc": "The Five of Spades. Associated with change and challenge, a card of adaptation."},
    {"name": "♠ Four of Spades",    "image": "assets/cards/Spade/4.png",      "category": "Playing Cards", "desc": "The Four of Spades. Represents stability and foundation, a grounding card."},
    {"name": "♠ Three of Spades",   "image": "assets/cards/Spade/3.png",      "category": "Playing Cards", "desc": "The Three of Spades. A card of growth and expansion, often called the beginning."},
    {"name": "♠ Two of Spades",     "image": "assets/cards/Spade/2.png",      "category": "Playing Cards", "desc": "The Two of Spades. Represents duality and partnership, a card of choices."},
    
    {"name": "♥ Ace of Hearts",     "image": "assets/cards/Heart/A.png",      "category": "Playing Cards", "desc": "The Ace of Hearts. Symbol of love and passion, the beginning of emotional journeys."},
    {"name": "♥ King of Hearts",    "image": "assets/cards/Heart/K.png",      "category": "Playing Cards", "desc": "The King of Hearts. A symbol of love and passion, often depicted as a noble figure."},
    {"name": "♥ Queen of Hearts",   "image": "assets/cards/Heart/Q.png",      "category": "Playing Cards", "desc": "The Queen of Hearts. Rules with grace and compassion, a card of nurturing love."},
    {"name": "♥ Jack of Hearts",    "image": "assets/cards/Heart/J.png",      "category": "Playing Cards", "desc": "The Jack of Hearts. A symbol of youth and romance, often depicted as a charming figure."},
    {"name": "♥ Ten of Hearts",     "image": "assets/cards/Heart/10.png",     "category": "Playing Cards", "desc": "The Ten of Hearts. Represents happiness and fulfillment, a card of contentment."},
    {"name": "♥ Nine of Hearts",    "image": "assets/cards/Heart/9.png",      "category": "Playing Cards", "desc": "The Nine of Hearts. The wish card, brings hope and unexpected turns of fortune."},
    {"name": "♥ Eight of Hearts",   "image": "assets/cards/Heart/8.png",      "category": "Playing Cards", "desc": "The Eight of Hearts. Represents abundance and generosity, a card of emotional wealth."},
    {"name": "♥ Seven of Hearts",   "image": "assets/cards/Heart/7.png",      "category": "Playing Cards", "desc": "The Seven of Hearts. A card of spiritual love and deep emotional connection."},
    {"name": "♥ Six of Hearts",     "image": "assets/cards/Heart/6.png",      "category": "Playing Cards", "desc": "The Six of Hearts. Represents gratitude and reunions, a card of reconciliation."},
    {"name": "♥ Five of Hearts",    "image": "assets/cards/Heart/5.png",      "category": "Playing Cards", "desc": "The Five of Hearts. A card of personal challenge and emotional growth through adversity."},
    {"name": "♥ Four of Hearts",    "image": "assets/cards/Heart/4.png",      "category": "Playing Cards", "desc": "The Four of Hearts. Represents peace and stability in relationships and home."},
    {"name": "♥ Three of Hearts",   "image": "assets/cards/Heart/3.png",      "category": "Playing Cards", "desc": "The Three of Hearts. A card of celebration and creative expression of love."},
    {"name": "♥ Two of Hearts",     "image": "assets/cards/Heart/2.png",      "category": "Playing Cards", "desc": "The Two of Hearts. Represents partnership and mutual affection, a card of bonds."},
    
    {"name": "♦ Ace of Diamonds",   "image": "assets/cards/Diamond/A.png",    "category": "Playing Cards", "desc": "The Ace of Diamonds. Symbol of wealth and new financial beginnings."},
    {"name": "♦ King of Diamonds",  "image": "assets/cards/Diamond/K.png",    "category": "Playing Cards", "desc": "The King of Diamonds. Rules wealth and abundance with wisdom and experience."},
    {"name": "♦ Queen of Diamonds", "image": "assets/cards/Diamond/Q.png",    "category": "Playing Cards", "desc": "The Queen of Diamonds. Represents wealth and elegance, often portrayed as a regal figure."},
    {"name": "♦ Jack of Diamonds",  "image": "assets/cards/Diamond/J.png",    "category": "Playing Cards", "desc": "The Jack of Diamonds. A symbol of commerce and practical business intelligence."},
    {"name": "♦ Ten of Diamonds",   "image": "assets/cards/Diamond/10.png",   "category": "Playing Cards", "desc": "The Ten of Diamonds. Represents success and wealth accumulation, prosperity achieved."},
    {"name": "♦ Nine of Diamonds",  "image": "assets/cards/Diamond/9.png",    "category": "Playing Cards", "desc": "The Nine of Diamonds. A card of wisdom in financial matters and material concerns."},
    {"name": "♦ Eight of Diamonds", "image": "assets/cards/Diamond/8.png",    "category": "Playing Cards", "desc": "The Eight of Diamonds. Steady and balanced, a dependable mid-range card."},
    {"name": "♦ Seven of Diamonds", "image": "assets/cards/Diamond/7.png",    "category": "Playing Cards", "desc": "The Seven of Diamonds. A card of analytical thinking and practical solutions."},
    {"name": "♦ Six of Diamonds",   "image": "assets/cards/Diamond/6.png",    "category": "Playing Cards", "desc": "The Six of Diamonds. Represents fair exchange and harmonious business dealings."},
    {"name": "♦ Five of Diamonds",  "image": "assets/cards/Diamond/5.png",    "category": "Playing Cards", "desc": "The Five of Diamonds. A card of resourcefulness and making do with what you have."},
    {"name": "♦ Four of Diamonds",  "image": "assets/cards/Diamond/4.png",    "category": "Playing Cards", "desc": "The Four of Diamonds. Represents stability in finance and secure foundations."},
    {"name": "♦ Three of Diamonds", "image": "assets/cards/Diamond/3.png",    "category": "Playing Cards", "desc": "The Three of Diamonds. A card of growth in business and expanding opportunities."},
    {"name": "♦ Two of Diamonds",   "image": "assets/cards/Diamond/2.png",    "category": "Playing Cards", "desc": "The Two of Diamonds. Represents balance in financial dealings and mutual benefit."},
    
    {"name": "♣ Ace of Clubs",      "image": "assets/cards/Spade/A.png",       "category": "Playing Cards", "desc": "The Ace of Clubs. Symbol of nature and new beginnings in material matters."},
    {"name": "♣ King of Clubs",     "image": "assets/cards/Spade/K.png",       "category": "Playing Cards", "desc": "The King of Clubs. A practical and grounded leader, wise in earthly matters."},
    {"name": "♣ Queen of Clubs",    "image": "assets/cards/Spade/Q.png",       "category": "Playing Cards", "desc": "The Queen of Clubs. Represents nurturing abundance and practical care for others."},
    {"name": "♣ Jack of Clubs",     "image": "assets/cards/Spade/J.png",       "category": "Playing Cards", "desc": "The Jack of Clubs. A symbol of youth and energy, often depicted as a lively character."},
    {"name": "♣ Ten of Clubs",      "image": "assets/cards/Spade/10.png",      "category": "Playing Cards", "desc": "The Ten of Clubs. Represents success through teamwork and collective effort."},
    {"name": "♣ Nine of Clubs",     "image": "assets/cards/Spade/9.png",       "category": "Playing Cards", "desc": "The Nine of Clubs. A card of material gain and positive news regarding finances."},
    {"name": "♣ Eight of Clubs",    "image": "assets/cards/Spade/8.png",       "category": "Playing Cards", "desc": "The Eight of Clubs. Represents skill and craftsmanship in practical matters."},
    {"name": "♣ Seven of Clubs",    "image": "assets/cards/Spade/7.png",       "category": "Playing Cards", "desc": "The Seven of Clubs. Lucky number seven, fortune favors the bold."},
    {"name": "♣ Six of Clubs",      "image": "assets/cards/Spade/6.png",       "category": "Playing Cards", "desc": "The Six of Clubs. Represents harmony in work and good progress in endeavors."},
    {"name": "♣ Five of Clubs",     "image": "assets/cards/Spade/5.png",       "category": "Playing Cards", "desc": "The Five of Clubs. A card of challenge overcome through determination and effort."},
    {"name": "♣ Four of Clubs",     "image": "assets/cards/Spade/4.png",       "category": "Playing Cards", "desc": "The Four of Clubs. Represents solid foundations and lasting security."},
    {"name": "♣ Three of Clubs",    "image": "assets/cards/Spade/3.png",       "category": "Playing Cards", "desc": "The Three of Clubs. A card of growth in practical matters and expanding ventures."},
    {"name": "♣ Two of Clubs",      "image": "assets/cards/Spade/2.png",       "category": "Playing Cards", "desc": "The Two of Clubs. Represents balance in work and good partnerships in business."},

    {"name": "♤ Ace of Spades",     "image": "assets/cards/Spade/A.png",      "category": "Playing Cards", "desc": "The Ace of Spades. The highest card in the deck, often associated with good luck and power."},
    {"name": "King of Spades",    "image": "assets/cards/Spade/K.png",      "category": "Playing Cards", "desc": "The King of Spades. A symbol of authority and strength, wielding the sword with honor."},
    {"name": "Queen of Spades",   "image": "assets/cards/Spade/Q.png",      "category": "Playing Cards", "desc": "The Queen of Spades. A symbol of wisdom and strategy, often associated with mystery."},
    {"name": "Jack of Spades",    "image": "assets/cards/Spade/J.png",      "category": "Playing Cards", "desc": "The Jack of Spades. A symbol of cunning and wit, often depicted as a clever rogue."},
    {"name": "Ten of Spades",     "image": "assets/cards/Spade/10.png",     "category": "Playing Cards", "desc": "The Ten of Spades. Represents completion and fulfillment, often associated with victory."},
    {"name": "Nine of Spades",    "image": "assets/cards/Spade/9.png",      "category": "Playing Cards", "desc": "The Nine of Spades. A card of reflection and introspection, symbolizing inner strength."},
    {"name": "Eight of Spades",   "image": "assets/cards/Spade/8.png",      "category": "Playing Cards", "desc": "The Eight of Spades. Represents balance and infinity, often associated with cycles."},
    {"name": "Seven of Spades",   "image": "assets/cards/Spade/7.png",      "category": "Playing Cards", "desc": "The Seven of Spades. A magical number, often associated with luck and mystery."},
    {"name": "Six of Spades",     "image": "assets/cards/Spade/6.png",      "category": "Playing Cards", "desc": "The Six of Spades. Represents harmony and balance, a card of negotiation."},
    {"name": "Five of Spades",    "image": "assets/cards/Spade/5.png",      "category": "Playing Cards", "desc": "The Five of Spades. Associated with change and challenge, a card of adaptation."},
    {"name": "Four of Spades",    "image": "assets/cards/Spade/4.png",      "category": "Playing Cards", "desc": "The Four of Spades. Represents stability and foundation, a grounding card."},
    {"name": "Three of Spades",   "image": "assets/cards/Spade/3.png",      "category": "Playing Cards", "desc": "The Three of Spades. A card of growth and expansion, often called the beginning."},
    {"name": "Two of Spades",     "image": "assets/cards/Spade/2.png",      "category": "Playing Cards", "desc": "The Two of Spades. Represents duality and partnership, a card of choices."},
    
    {"name": "Ace of Hearts",     "image": "assets/cards/Heart/A.png",      "category": "Playing Cards", "desc": "The Ace of Hearts. Symbol of love and passion, the beginning of emotional journeys."},
    {"name": "King of Hearts",    "image": "assets/cards/Heart/K.png",      "category": "Playing Cards", "desc": "The King of Hearts. A symbol of love and passion, often depicted as a noble figure."},
    {"name": "Queen of Hearts",   "image": "assets/cards/Heart/Q.png",      "category": "Playing Cards", "desc": "The Queen of Hearts. Rules with grace and compassion, a card of nurturing love."},
    {"name": "Jack of Hearts",    "image": "assets/cards/Heart/J.png",      "category": "Playing Cards", "desc": "The Jack of Hearts. A symbol of youth and romance, often depicted as a charming figure."},
    {"name": "Ten of Hearts",     "image": "assets/cards/Heart/10.png",     "category": "Playing Cards", "desc": "The Ten of Hearts. Represents happiness and fulfillment, a card of contentment."},
    {"name": "Nine of Hearts",    "image": "assets/cards/Heart/9.png",      "category": "Playing Cards", "desc": "The Nine of Hearts. The wish card, brings hope and unexpected turns of fortune."},
    {"name": "Eight of Hearts",   "image": "assets/cards/Heart/8.png",      "category": "Playing Cards", "desc": "The Eight of Hearts. Represents abundance and generosity, a card of emotional wealth."},
    {"name": "Seven of Hearts",   "image": "assets/cards/Heart/7.png",      "category": "Playing Cards", "desc": "The Seven of Hearts. A card of spiritual love and deep emotional connection."},
    {"name": "Six of Hearts",     "image": "assets/cards/Heart/6.png",      "category": "Playing Cards", "desc": "The Six of Hearts. Represents gratitude and reunions, a card of reconciliation."},
    {"name": "Five of Hearts",    "image": "assets/cards/Heart/5.png",      "category": "Playing Cards", "desc": "The Five of Hearts. A card of personal challenge and emotional growth through adversity."},
    {"name": "Four of Hearts",    "image": "assets/cards/Heart/4.png",      "category": "Playing Cards", "desc": "The Four of Hearts. Represents peace and stability in relationships and home."},
    {"name": "Three of Hearts",   "image": "assets/cards/Heart/3.png",      "category": "Playing Cards", "desc": "The Three of Hearts. A card of celebration and creative expression of love."},
    {"name": "Two of Hearts",     "image": "assets/cards/Heart/2.png",      "category": "Playing Cards", "desc": "The Two of Hearts. Represents partnership and mutual affection, a card of bonds."},
    
    {"name": "Ace of Diamonds",   "image": "assets/cards/Diamond/A.png",    "category": "Playing Cards", "desc": "The Ace of Diamonds. Symbol of wealth and new financial beginnings."},
    {"name": "King of Diamonds",  "image": "assets/cards/Diamond/K.png",    "category": "Playing Cards", "desc": "The King of Diamonds. Rules wealth and abundance with wisdom and experience."},
    {"name": "Queen of Diamonds", "image": "assets/cards/Diamond/Q.png",    "category": "Playing Cards", "desc": "The Queen of Diamonds. Represents wealth and elegance, often portrayed as a regal figure."},
    {"name": "Jack of Diamonds",  "image": "assets/cards/Diamond/J.png",    "category": "Playing Cards", "desc": "The Jack of Diamonds. A symbol of commerce and practical business intelligence."},
    {"name": "Ten of Diamonds",   "image": "assets/cards/Diamond/10.png",   "category": "Playing Cards", "desc": "The Ten of Diamonds. Represents success and wealth accumulation, prosperity achieved."},
    {"name": "Nine of Diamonds",  "image": "assets/cards/Diamond/9.png",    "category": "Playing Cards", "desc": "The Nine of Diamonds. A card of wisdom in financial matters and material concerns."},
    {"name": "Eight of Diamonds", "image": "assets/cards/Diamond/8.png",    "category": "Playing Cards", "desc": "The Eight of Diamonds. Steady and balanced, a dependable mid-range card."},
    {"name": "Seven of Diamonds", "image": "assets/cards/Diamond/7.png",    "category": "Playing Cards", "desc": "The Seven of Diamonds. A card of analytical thinking and practical solutions."},
    {"name": "Six of Diamonds",   "image": "assets/cards/Diamond/6.png",    "category": "Playing Cards", "desc": "The Six of Diamonds. Represents fair exchange and harmonious business dealings."},
    {"name": "Five of Diamonds",  "image": "assets/cards/Diamond/5.png",    "category": "Playing Cards", "desc": "The Five of Diamonds. A card of resourcefulness and making do with what you have."},
    {"name": "Four of Diamonds",  "image": "assets/cards/Diamond/4.png",    "category": "Playing Cards", "desc": "The Four of Diamonds. Represents stability in finance and secure foundations."},
    {"name": "Three of Diamonds", "image": "assets/cards/Diamond/3.png",    "category": "Playing Cards", "desc": "The Three of Diamonds. A card of growth in business and expanding opportunities."},
    {"name": "Two of Diamonds",   "image": "assets/cards/Diamond/2.png",    "category": "Playing Cards", "desc": "The Two of Diamonds. Represents balance in financial dealings and mutual benefit."},
    
    {"name": "Ace of Clubs",      "image": "assets/cards/Spade/A.png",       "category": "Playing Cards", "desc": "The Ace of Clubs. Symbol of nature and new beginnings in material matters."},
    {"name": "King of Clubs",     "image": "assets/cards/Spade/K.png",       "category": "Playing Cards", "desc": "The King of Clubs. A practical and grounded leader, wise in earthly matters."},
    {"name": "Queen of Clubs",    "image": "assets/cards/Spade/Q.png",       "category": "Playing Cards", "desc": "The Queen of Clubs. Represents nurturing abundance and practical care for others."},
    {"name": "Jack of Clubs",     "image": "assets/cards/Spade/J.png",       "category": "Playing Cards", "desc": "The Jack of Clubs. A symbol of youth and energy, often depicted as a lively character."},
    {"name": "Ten of Clubs",      "image": "assets/cards/Spade/10.png",      "category": "Playing Cards", "desc": "The Ten of Clubs. Represents success through teamwork and collective effort."},
    {"name": "Nine of Clubs",     "image": "assets/cards/Spade/9.png",       "category": "Playing Cards", "desc": "The Nine of Clubs. A card of material gain and positive news regarding finances."},
    {"name": "Eight of Clubs",    "image": "assets/cards/Spade/8.png",       "category": "Playing Cards", "desc": "The Eight of Clubs. Represents skill and craftsmanship in practical matters."},
    {"name": "Seven of Clubs",    "image": "assets/cards/Spade/7.png",       "category": "Playing Cards", "desc": "The Seven of Clubs. Lucky number seven, fortune favors the bold."},
    {"name": "Six of Clubs",      "image": "assets/cards/Spade/6.png",       "category": "Playing Cards", "desc": "The Six of Clubs. Represents harmony in work and good progress in endeavors."},
    {"name": "Five of Clubs",     "image": "assets/cards/Spade/5.png",       "category": "Playing Cards", "desc": "The Five of Clubs. A card of challenge overcome through determination and effort."},
    {"name": "Four of Clubs",     "image": "assets/cards/Spade/4.png",       "category": "Playing Cards", "desc": "The Four of Clubs. Represents solid foundations and lasting security."},
    {"name": "Three of Clubs",    "image": "assets/cards/Spade/3.png",       "category": "Playing Cards", "desc": "The Three of Clubs. A card of growth in practical matters and expanding ventures."},
    {"name": "Two of Clubs",      "image": "assets/cards/Spade/2.png",       "category": "Playing Cards", "desc": "The Two of Clubs. Represents balance in work and good partnerships in business."},

    # -- joker cards ---
    {"name": "Red Joker",         "image": "assets/cards/joker/joker_red.png",         "category": "Joker", "desc": "The Red Joker. A wild card that can represent anything, often associated with chaos and unpredictability."},
    {"name": "Black Joker",       "image": "assets/cards/joker/joker_black.png",       "category": "Joker", "desc": "The Black Joker. A wild card that can represent anything, often associated with mystery and mischief."},
    {"name": "White Joker",       "image": "assets/cards/joker/joker_white.png",       "category": "Joker", "desc": "The Color Joker. A wild card that can represent anything, often associated with creativity and versatility."},
    {"name": "Blank Joker",       "image": "assets/cards/joker/joker_blank.png",       "category": "Joker", "desc": "The Blank Joker. A wild card that can represent anything, often associated with potential and possibility."},


    # -- tarot cards ---
    {"name": "The Fool",          "image": "assets/cards/tarot/fool.png",          "category": "Tarot", "desc": "The Fool. Represents new beginnings, innocence, and a free spirit."},
    {"name": "The Magician",      "image": "assets/cards/tarot/magician.png",      "category": "Tarot", "desc": "The Magician. Symbolizes manifestation, resourcefulness, and power."},
    {"name": "The High Priestess", "image": "assets/cards/tarot/high_priestess.png", "category": "Tarot", "desc": "The High Priestess. Represents intuition, mystery, and the subconscious mind."},
    {"name": "The Empress",       "image": "assets/cards/tarot/empress.png",       "category": "Tarot", "desc": "The Empress. Symbolizes fertility, abundance, and nurturing."},
    {"name": "The Emperor",       "image": "assets/cards/tarot/emperor.png",       "category": "Tarot", "desc": "The Emperor. Represents authority, structure, and control."},
    {"name": "The Hierophant",    "image": "assets/cards/tarot/hierophant.png",    "category": "Tarot", "desc": "The Hierophant. Symbolizes tradition, conformity, and spiritual guidance."},
    {"name": "The Lovers",       "image": "assets/cards/tarot/lovers.png",       "category": "Tarot", "desc": "The Lovers. Represents love, harmony, and choices."},
    {"name": "The Chariot",      "image": "assets/cards/tarot/chariot.png",      "category": "Tarot", "desc": "The Chariot. Symbolizes victory, determination, and willpower."},
    {"name": "Strength",         "image": "assets/cards/tarot/strength.png",     "category": "Tarot", "desc": "Strength. Represents courage, patience, and inner strength."},
    {"name": "The Hermit",       "image": "assets/cards/tarot/hermit.png",       "category": "Tarot", "desc": "The Hermit. Symbolizes introspection, solitude, and guidance."},
    {"name": "Wheel of Fortune", "image": "assets/cards/tarot/wheel_of_fortune.png", "category": "Tarot", "desc": "Wheel of Fortune. Represents change, cycles, and fate."},
    {"name": "Justice",          "image": "assets/cards/tarot/justice.png",      "category": "Tarot", "desc": "Justice. Symbolizes fairness, truth, and law."},
    {"name": "The Hanged Man", "image": "assets/cards/tarot/hanged_man.png", "category": "Tarot", "desc": "The Hanged Man. Represents suspension, letting go, and new perspectives."},
    {"name": "Death",           "image": "assets/cards/tarot/death.png",           "category": "Tarot", "desc": "Death. Symbolizes transformation, endings, and new beginnings."},
    {"name": "Temperance",      "image": "assets/cards/tarot/temperance.png",      "category": "Tarot", "desc": "Temperance. Represents balance, moderation, and harmony."},
    {"name": "The Devil",       "image": "assets/cards/tarot/devil.png",       "category": "Tarot", "desc": "The Devil. Symbolizes temptation, materialism, and bondage."},
    {"name": "The Tower",       "image": "assets/cards/tarot/tower.png",       "category": "Tarot", "desc": "The Tower. Represents sudden change, upheaval, and revelation."},
    {"name": "The Star",        "image": "assets/cards/tarot/star.png",        "category": "Tarot", "desc": "The Star. Symbolizes hope, inspiration, and serenity."},
    {"name": "The Moon",        "image": "assets/cards/tarot/moon.png",        "category": "Tarot", "desc": "The Moon. Represents illusion, fear, and the subconscious."},
    {"name": "The Sun",         "image": "assets/cards/tarot/sun.png",         "category": "Tarot", "desc": "The Sun. Symbolizes positivity, success, and vitality."},
    {"name": "Judgement",       "image": "assets/cards/tarot/judgement.png",       "category": "Tarot", "desc": "Judgement. Represents rebirth, inner calling, and absolution."},
    


    # --- mahjong ---
    {"name": "One Bamboo",       "image": "assets/cards/mahjong/bamboo1.png",       "category": "Mahjong", "desc": "The One Bamboo tile. A simple yet essential piece in Mahjong."},
    {"name": "Two Bamboo",       "image": "assets/cards/mahjong/bamboo2.png",       "category": "Mahjong", "desc": "The Two Bamboo tile. A common piece used in many Mahjong hands."},
    {"name": "Three Bamboo",     "image": "assets/cards/mahjong/bamboo3.png",       "category": "Mahjong", "desc": "The Three Bamboo tile. A versatile piece that can fit into various combinations."},
    {"name": "Four Bamboo",      "image": "assets/cards/mahjong/bamboo4.png",       "category": "Mahjong", "desc": "The Four Bamboo tile. A building block for many Mahjong hands."},
    {"name": "Five Bamboo",      "image": "assets/cards/mahjong/bamboo5.png",       "category": "Mahjong", "desc": "The Five Bamboo tile. A key piece for completing certain Mahjong hands."},
    {"name": "Six Bamboo",       "image": "assets/cards/mahjong/bamboo6.png",       "category": "Mahjong", "desc": "The Six Bamboo tile. A common piece that can be used in various combinations."},
    {"name": "Seven Bamboo",     "image": "assets/cards/mahjong/bamboo7.png",       "category": "Mahjong", "desc": "The Seven Bamboo tile. A versatile piece that can fit into many Mahjong hands."},
    {"name": "Eight Bamboo",     "image": "assets/cards/mahjong/bamboo8.png",       "category": "Mahjong", "desc": "The Eight Bamboo tile. A building block for completing Mahjong hands."},
    {"name": "Nine Bamboo",      "image": "assets/cards/mahjong/bamboo9.png",       "category": "Mahjong", "desc": "The Nine Bamboo tile. A key piece for finishing certain Mahjong hands."},   
    {"name": "Chrysanthemum",      "image": "assets/cards/mahjong/chrysanthemum.png",       "category": "Mahjong", "desc": "The Chrysanthemum tile. A beautiful and valuable piece in Mahjong."},  
    {"name": "One Circle",      "image": "assets/cards/mahjong/circle1.png",       "category": "Mahjong", "desc": "The One Circle tile. A simple yet essential piece in Mahjong ."},   
    {"name": "Two Circle",      "image": "assets/cards/mahjong/circle2.png",       "category": "Mahjong", "desc": "The Two Circle tile. A common piece used in many Mahjong hands."},   
    {"name": "Three Circle",    "image": "assets/cards/mahjong/circle3.png",       "category": "Mahjong", "desc": "The Three Circle tile. A versatile piece that can fit into various combinations."},   
    {"name": "Four Circle",     "image": "assets/cards/mahjong/circle4.png",       "category": "Mahjong", "desc": "The Four Circle tile. A building block for many Mahjong hands."},   
    {"name": "Five Circle",     "image": "assets/cards/mahjong/circle5.png",       "category": "Mahjong", "desc": "The Five Circle tile. A key piece for completing certain Mahjong hands."},   
    {"name": "Six Circle",      "image": "assets/cards/mahjong/circle6.png",       "category": "Mahjong", "desc": "The Six Circle tile. A common piece that can be used in various combinations."},   
    {"name": "Seven Circle",    "image": "assets/cards/mahjong/circle7.png",       "category": "Mahjong", "desc": "The Seven Circle tile. A versatile piece that can fit into many Mahjong hands."},   
    {"name": "Eight Circle",    "image": "assets/cards/mahjong/circle8.png",       "category": "Mahjong", "desc": "The Eight Circle tile. A building block for completing Mahjong hands."},   
    {"name": "Nine Circle",     "image": "assets/cards/mahjong/circle9.png",       "category": "Mahjong", "desc": "The Nine Circle tile. A key piece for finishing certain Mahjong hands."},
    {"name": "Fall",     "image": "assets/cards/mahjong/fall.png",       "category": "Mahjong", "desc": "The Fall tile. A symbol of change and transition in Mahjong."},
    {"name": "Lotus",     "image": "assets/cards/mahjong/lotus.png",       "category": "Mahjong", "desc": "The Lotus tile. Represents purity and enlightenment in Mahjong."},
    {"name": "Orchid",     "image": "assets/cards/mahjong/orchid.png",       "category": "Mahjong", "desc": "The Orchid tile. A symbol of elegance and beauty in Mahjong."},
    {"name": "Peony",     "image": "assets/cards/mahjong/peony.png",       "category": "Mahjong", "desc": "The Peony tile. Represents wealth and prosperity in Mahjong."},
    {"name": "One Pinyin",     "image": "assets/cards/mahjong/pinyin1.png",       "category": "Mahjong", "desc": "The One Pinyin tile. A common piece used in many Mahjong hands."},
    {"name": "Two Pinyin",     "image": "assets/cards/mahjong/pinyin2.png",       "category": "Mahjong", "desc": "The Two Pinyin tile. A common piece used in many Mahjong hands."},
    {"name": "Three Pinyin",     "image": "assets/cards/mahjong/pinyin3.png",       "category": "Mahjong", "desc": "The Three Pinyin tile. A versatile piece that can fit into various combinations."},
    {"name": "Four Pinyin",     "image": "assets/cards/mahjong/pinyin4.png",       "category": "Mahjong", "desc": "The Four Pinyin tile. A building block for many Mahjong hands."},
    {"name": "Five Pinyin",     "image": "assets/cards/mahjong/pinyin5.png",       "category": "Mahjong", "desc": "The Five Pinyin tile. A key piece for completing certain Mahjong hands."},
    {"name": "Six Pinyin",     "image": "assets/cards/mahjong/pinyin6.png",       "category": "Mahjong", "desc": "The Six Pinyin tile. A common piece that can be used in various combinations."},
    {"name": "Seven Pinyin",     "image": "assets/cards/mahjong/pinyin7.png",       "category": "Mahjong", "desc": "The Seven Pinyin tile. A versatile piece that can fit into many Mahjong hands."},
    {"name": "Eight Pinyin",     "image": "assets/cards/mahjong/pinyin8.png",       "category": "Mahjong", "desc": "The Eight Pinyin tile. A building block for completing Mahjong hands."},
    {"name": "Nine Pinyin",     "image": "assets/cards/mahjong/pinyin9.png",       "category": "Mahjong", "desc": "The Nine Pinyin tile. A key piece for finishing certain Mahjong hands."},
    
    {"name": "Red Dragon",     "image": "assets/cards/mahjong/red_dragon.png",       "category": "Mahjong", "desc": "The Red Dragon tile. A powerful piece that can significantly impact the game."},
    {"name": "Green Dragon",     "image": "assets/cards/mahjong/green_dragon.png",       "category": "Mahjong", "desc": "The Green Dragon tile. A valuable piece that can help complete certain hands."},
    {"name": "White Dragon",     "image": "assets/cards/mahjong/white_dragon.png",       "category": "Mahjong", "desc": "The White Dragon tile. A versatile piece that can fit into various combinations."},
    {"name": "North Wind",     "image": "assets/cards/mahjong/north_wind.png",       "category": "Mahjong", "desc": "The North Wind tile. Represents the north direction and can be a valuable piece in Mahjong."},
    {"name": "East Wind",     "image": "assets/cards/mahjong/east_wind.png",       "category": "Mahjong", "desc": "The East Wind tile. Represents the east direction and can be a valuable piece in Mahjong."},
    {"name": "South Wind",     "image": "assets/cards/mahjong/south_wind.png",       "category": "Mahjong", "desc": "The South Wind tile. Represents the south direction and can be a valuable piece in Mahjong."},
    {"name": "West Wind",     "image": "assets/cards/mahjong/west_wind.png",       "category": "Mahjong", "desc": "The West Wind tile. Represents the west direction and can be a valuable piece in Mahjong."},

    {"name": "Spring",     "image": "assets/cards/mahjong/spring.png",       "category": "Mahjong", "desc": "The Spring tile. A symbol of renewal and growth in Mahjong."},
    {"name": "Summer",     "image": "assets/cards/mahjong/summer.png",       "category": "Mahjong", "desc": "The Summer tile. A symbol of vitality and energy in Mahjong."},
    {"name": "Autumn",     "image": "assets/cards/mahjong/autumn.png",       "category": "Mahjong", "desc": "The Autumn tile. A symbol of harvest and reflection in Mahjong."},
    {"name": "Winter",     "image": "assets/cards/mahjong/winter.png",       "category": "Mahjong", "desc": "The Winter tile. A symbol of rest and preparation in Mahjong."},

    # --- Holy / Units ---
    {"name": "Holy Knight",     "image": "assets/card_holy_knight.png",      "category": "Units", "desc": "A divine warrior clad in blessed armor. Strikes with holy fury."},
    {"name": "Holy Archer",     "image": "assets/card_holy_archer.png",      "category": "Units", "desc": "A sacred marksman. Fires arrows of light at distant foes."},
    {"name": "Holy Mage",       "image": "assets/card_holy_mage.png",        "category": "Units", "desc": "A priest of arcane power. Casts healing and offensive miracles."},
    {"name": "Castle",          "image": "assets/card_castle.png",           "category": "Units", "desc": "A fortified stronghold. Provides defense and rallies nearby units."},
    {"name": "Keep",            "image": "assets/card_keep.png",             "category": "Units", "desc": "The inner fortress. Last line of defense with reinforced walls."},
    {"name": "Footman",         "image": "assets/card_footman.png",          "category": "Units", "desc": "A reliable infantry soldier. Holds the front line with shield and sword."},
    {"name": "Rifleman",        "image": "assets/card_rifleman.png",         "category": "Units", "desc": "A ranged combatant with a rifle. Picks off enemies from a distance."},
    {"name": "Knight",          "image": "assets/card_knight.png",           "category": "Units", "desc": "A mounted warrior. Charges into battle with devastating momentum."},
    {"name": "Stronghold",      "image": "assets/card_stronghold.png",       "category": "Units", "desc": "A massive fortification. Nearly impenetrable and boosts garrison morale."},
    {"name": "Grunt",           "image": "assets/card_grunt.png",            "category": "Units", "desc": "A basic but fierce orc warrior. Fights with raw aggression."},
    {"name": "Burrow",          "image": "assets/card_burrow.png",           "category": "Units", "desc": "An underground hideout. Conceals units and enables surprise attacks."},
    {"name": "Ghoul",           "image": "assets/card_ghoul.png",            "category": "Units", "desc": "An undead scavenger. Regenerates health by consuming fallen foes."},
    {"name": "Blue Eyes Dragon","image": "assets/card_blue_eyes_white_dragon.png","category": "Units", "desc": "The legendary Blue-Eyes White Dragon. Devastating burst stream of destruction."},
    {"name": "Red Eyes Dragon", "image": "assets/card_red_eyes_black_dragon.png", "category": "Units", "desc": "The fierce Red-Eyes Black Dragon. Inferno fire blast incinerates all."},
    {"name": "Moon Champion",   "image": "assets/card_moon_champion.png",    "category": "Units", "desc": "A warrior empowered by moonlight. Grows stronger as night falls."},
    {"name": "Lunar Soldier",   "image": "assets/card_soldier_of_lunar_light.png","category": "Units", "desc": "A soldier blessed by the moon. Fights with ethereal lunar energy."},
    {"name": "Void Bard",       "image": "assets/card_void_bard.png",        "category": "Units", "desc": "A musician of the void. Plays haunting melodies that weaken enemies."},
    # --- Spells / Traps ---
    {"name": "Trap Stun",       "image": "assets/card_trap_stun.png",        "category": "Spells", "desc": "Negates all trap cards for this turn. Clears the way for your play."},
    {"name": "Barbed Armour",   "image": "assets/card_barbed_armour.png",    "category": "Spells", "desc": "Reflects a portion of damage back to the attacker. Punishes aggression."},
    {"name": "Swords of Hope",  "image": "assets/swords_of_hope_card.png",   "category": "Spells", "desc": "Protective swords that shield you. Stalls the opponent for multiple turns."},
    {"name": "Whip",            "image": "assets/whip_card.png",             "category": "Spells", "desc": "A swift lashing attack. Deals damage and reduces enemy defense."},
    {"name": "Silence",         "image": "assets/silence_card.png",          "category": "Spells", "desc": "Mutes the opponent's special abilities for one turn. Pure suppression."},
    {"name": "Greater Axe",     "image": "assets/greater_axe_card.png",      "category": "Spells", "desc": "A massive enchanted axe. Boosts attack power significantly."},
    {"name": "Black Hole",      "image": "assets/blackhole_card.png",        "category": "Spells", "desc": "Destroys all cards on the field. A devastating reset for both sides."},
    {"name": "Mystical Typhoon","image": "assets/mysticalspacetypoon_card.png","category": "Spells", "desc": "Destroys one spell or trap card on the field. Precise removal."},
    # --- AA (Action Arena) ---
    {"name": "AA Shoot",        "image": "assets/card_aa_shoot.png",         "category": "AA", "desc": "Fire your weapon in the Action Arena. Deals direct damage."},
    {"name": "AA Reload",       "image": "assets/card_aa_reload.png",        "category": "AA", "desc": "Reload your ammunition. Required before you can shoot again."},
    {"name": "AA Block",        "image": "assets/card_aa_block.png",         "category": "AA", "desc": "Raise your shield to block an incoming shot. Negates damage."},
    {"name": "AA Can't Shoot",  "image": "assets/card_aa_cant_shoot.png",    "category": "AA", "desc": "Prevents the opponent from shooting next turn. Tactical denial."},
    {"name": "AA Reflect Shot", "image": "assets/card_aa_reflect_shot.png",  "category": "AA", "desc": "Reflects an incoming shot back at the attacker. Risky but rewarding."},
    {"name": "AA Extra Heart",  "image": "assets/card_aa_extra_heart.png",   "category": "AA", "desc": "Grants one additional life point. Extends your survival in the arena."},
    {"name": "AA Reset",        "image": "assets/card_aa_reset_players.png", "category": "AA", "desc": "Resets both players to their starting state. A full arena restart."},
]